### ISSUE TITLE
Unwrapped version?

### ISSUE THREAD

**Issue by zzzsyyy** [colemickens/flake-firefox-nightly#9]
Is it possible to use something like `firefox-nightly-bin-unwrapped` or is there a method to define `extraPolicies` for firefox?

**Comment by colemickens** [comment]
To be honest, I'm really not sure. I'm not even sure if this one counts as "wrapped".

Is `extraPolicies` something that is usually used with the source pkg of firefox?

Any other hints appreciated, so far my answer is a disappointing :confused:  and :man_shrugging: .

**Comment by zzzsyyy** [comment]
I've solved it.

Just use `override` like

```nix
programs.firefox = {
    enable = true;
    package = pkgs.firefox-nightly-bin.override {
      extraPolicies = {
        DisablePocket = true;
      };
    };
};
```

**Comment by robbins** [comment]
I've tried to use an override to set the policies, but `about:policies` only shows `DisableAppUpdate`.

```
    programs.firefox = {
      enable = true;
      package = inputs.firefox-nightly.packages.${pkgs.system}.firefox-nightly-bin.override {
        extraPolicies = {
          # Privacy
          EnableTrackingProtection = {
            Value= true;
            Locked = true;
            Cryptomining = true;
            Fingerprinting = true;
          };
          DisablePocket = true;
          DontCheckDefaultBrowser = true;
        };
      };
```
